editing/routes.py
from flask import request, render_template, send_file, Blueprint, session
from editing.video_utils import *
import os

editing = Blueprint('editing', __name__, template_folder='templates')
fullpath = os.getcwd() + "\\editing\\"


@editing.route("/", methods=['GET'])
def edit_video():
    return render_template('editing.html')


@editing.route("/src/video.js", methods=['GET'])
def vue_file():
    return send_file(fullpath + "src\\" + "video.js")


@editing.route("/src/style.css", methods=['GET'])
def css():
    return send_file(fullpath + "src\\" + "style.css")


@editing.route("/clips/<filename>")
def render_clip(filename):
    path = fullpath + "clips\\" + filename
    print(path)
    return send_file(path)


@editing.route("/img/<filename>")
def render_img(filename):
    path = fullpath + "img\\" + filename
    print(path)
    session['img_file'] = path
    return send_file(session.get('img_file', str))


@editing.route("/upload", methods=['POST'])
def upload_video():
    # check if video save path exists
    if not os.path.isdir("./editing/clips"):
        os.mkdir("./editing/clips")
    try:
        video_file = request.files['videofile']
        longfilepath = fullpath + "clips\\" + video_file.filename
        # filepath = longfilepath[35:]
        video_file.save(longfilepath)
    except Exception as e:
        print(e)
    return str(longfilepath[35:])


# Main video editing pipeline
@editing.route('/edit_video/<actiontype>', methods=['POST'])
def editor(actiontype):
    if actiontype == "trim":
        try:
            video_file = request.form['videofile']
            path = fullpath + video_file
            edited_video_path = trim_video(path, int(request.form['trim_start']), int(request.form['trim_end']))
            return {
                "status": "success",
                "message": "video edit success",
                "edited_video_path": edited_video_path[35:]
            }
        except Exception as e:
            return {
                "status": "error",
                "message": "video edit failure: " + str(e),
            }
    elif actiontype == "image":
        try:
            video_file = request.form['videofile']
            path = fullpath + video_file
            edited_video_path = img_overlay(path, str(request.form['img_src']),
                                            int(request.form['start_time']),
                                            int(request.form['duration']), int(float(request.form['x_pos'])),
                                            int(float(request.form['y_pos'])))
            return {
                "status": "success",
                "message": "video edit success",
                "edited_video_path": edited_video_path[35:]
            }
        except Exception as e:
            return {
                "status": "error",
                "message": "video edit failure: " + str(e),
            }


@editing.route('/merged_render', methods=['POST'])
def merged_render():
    try:
        videoscount = int(request.form['videoscount'])
        if videoscount > 0:
            video_clip_filenames = []
            for i in range(videoscount):
                path = fullpath + request.form['video' + str(i)]
                video_clip_filenames.append(path)
            final_render_video_path = merge_videos(video_clip_filenames)[35:]
            print("final path is " + final_render_video_path)
            return {
                "status": "success",
                "message": "merged render success",
                "final_render_video_path": final_render_video_path
            }
        else:
            return {
                "status": "error",
                "message": "merged render error. Invalid videos count"
            }

    except Exception as e:
        return {
            "status": "error",
            "message": "video merge failure: " + str(e),
        }

routes.py
from flask import request, render_template, send_file, Blueprint, session
from video_utils import *
from config.definitions import ROOT_DIR, VIDEO_SAVE_DIR
import os

editing = Blueprint('editing', __name__, template_folder='templates')


@editing.route("/", methods=['GET'])
def edit_video():
    return render_template('editing.html')


@editing.route("/static/video.js", methods=['GET'])
def vue_file():
    return send_file("\\static\\" + "video.js")


@editing.route("/static/style.css", methods=['GET'])
def css():
    return send_file("\\static\\" + "style.css")


@editing.route("/clips/<filename>", methods=['GET'])
# use a transformer to get the high level path
def render_clip(filename):
    path = ROOT_DIR + VIDEO_SAVE_DIR + filename
    return send_file(path)


@editing.route("/img/<filename>")
def render_img(filename):
    path = ROOT_DIR + "\\img\\" + filename
    return send_file(path)


@editing.route("/upload", methods=['POST'])
def upload_video():
    # check if video save path exists
    if not os.path.isdir("./" + VIDEO_SAVE_DIR):
        os.mkdir("./" + VIDEO_SAVE_DIR)
    video_file = request.files['videofile']
    relative_path = VIDEO_SAVE_DIR + video_file.filename
    try:
        # https://towardsdatascience.com/simple-trick-to-work-with-relative-paths-in-python-c072cdc9acb9
        filepath = ROOT_DIR + VIDEO_SAVE_DIR + video_file.filename
        video_file.save(filepath)
    except Exception as e:
        print(e)
    return str(relative_path)


# Main video editing pipeline
@editing.route('/edit_video/<actiontype>', methods=['POST'])
def editor(actiontype):
    if actiontype == "trim":
        try:
            video_file = request.form['videofile']
            path = ROOT_DIR + video_file
            edited_video_path = trim_video(path, int(request.form['trim_start']), int(request.form['trim_end']))
            return {
                "status": "success",
                "message": "video edit success",
                "edited_video_path": edited_video_path
            }
        except Exception as e:
            return {
                "status": "error",
                "message": "video edit failure: " + str(e),
            }
    elif actiontype == "image":
        try:
            video_file = request.form['videofile']
            path = ROOT_DIR + video_file
            edited_video_path = img_overlay(path, str(request.form['img_src']),
                                            int(request.form['start_time']),
                                            int(request.form['duration']), int(float(request.form['x_pos'])),
                                            int(float(request.form['y_pos'])),  float(request.form['scale']))
            return {
                "status": "success",
                "message": "video edit success",
                "edited_video_path": edited_video_path
            }
        except Exception as e:
            return {
                "status": "error",
                "message": "video edit failure: " + str(e),
            }
    elif actiontype == "text":
        try:
            video_file = request.form['videofile']
            path = ROOT_DIR + video_file
            edited_video_path = text_overlay(path, str(request.form['title']),int(request.form['start_time']),int(request.form['duration']), int(float(request.form['x_pos'])), int(float(request.form['y_pos'])), int(request.form['fontsize']), str(request.form['color']))
            return {
                "status": "success",
                "message": "video edit success",
                "edited_video_path": edited_video_path
            }
        except Exception as e:
            return {
                "status": "error",
                "message": "video edit failure: " + str(e),
            }


@editing.route('/merged_render', methods=['POST'])
def merged_render():
    try:
        videoscount = int(request.form['videoscount'])
        if videoscount > 0:
            video_clip_filenames = []
            for i in range(videoscount):
                path = os.getcwd() + request.form['video' + str(i)]
                video_clip_filenames.append(path)
            final_render_video_path = merge_videos(video_clip_filenames)[35:]
            print("final path is " + final_render_video_path)
            return {
                "status": "success",
                "message": "merged render success",
                "final_render_video_path": final_render_video_path
            }
        else:
            return {
                "status": "error",
                "message": "merged render error. Invalid videos count"
            }

    except Exception as e:
        return {
            "status": "error",
            "message": "video merge failure: " + str(e),
        }

templates/editing.html
<!DOCTYPE html>
<html lang="en" xmlns:v-on="http://www.w3.org/1999/xhtml">
<head>
    <title>Step 2: Editing -- VideoLab</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="icon" type="image/x-icon" href="/static/favicon.ico">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <link href="https://vjs.zencdn.net/7.11.4/video-js.css" rel="stylesheet"/>
    <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">

</head>
<body>
<div class="row version-header" style="z-index:9999999999;">
    <div class="col"><h5 align="left">VideoLab v. 0.1 | <a href="/">Return to Home</a></h5></div>
    <div class="col"><h5 align="right" style="font-weight:bold">Step 2: Editing</h5></div>
</div>
<br> <br>
<div id="app">
    <div class="container-fluid">
        <br><br>
        <div class="row">
            <div style="text-align:center;">
                <h3>Video Render Preview</h3><br>
            </div>
        </div>
        <div class="row no-gutters" align="center">
            <span>
                <button v-on:click="removeVideo(index)" class="btn btn-danger">Delete Clip</button>
                <button class="btn btn-primary" id="upnew">Upload New Clip</button>
                </span>
        </div>
        <br> <br>
        <div v-if="videos.length" style="margin-left:25%;">
            <h3><u>[[videos[0].name]]</u></h3>
        </div>
        <div v-else style="margin-left:25%;">
            <h3>No Video Selected</h3>
        </div>
        <div align="center" class="row" style="position:relative;">
            <div class="drop-landing" id="editArea"></div>
            <div align="center">
                <video id="render" width="500" height="500" controls></video>
            </div>
        </div>
    </div>
    <br><br>
    <div class="row-lg-12" align="center">
            <span>
                <button class="btn btn-secondary btn-lg menu" id="shapebtn">Shape Annotations</button>
                <button class="btn btn-secondary btn-lg menu" id="textbtn">Text Annotations</button>
                <button class="btn btn-secondary btn-lg menu" id="trimbtn">Trim Video</button>
            </span>
    </div>
    <div id="shapepop" style="display: none">
        <img class="draggable" id="circle_lg"
             onmousedown="drag()"
             src="{{ url_for('editing.render_img', filename='circle_lg.png') }}"
             alt="A red circle.">
        <img class="draggable" id="circle_sm"
             onmousedown="drag()"
             src="{{ url_for('editing.render_img', filename='circle_sm.png') }}"
             alt="A red circle.">
        <img class="draggable" id="ar_right"
             onmousedown="drag()"
             src="{{ url_for('editing.render_img', filename='arrow_right.png') }}"
             alt="An arrow pointing up and to the right.">
        <img class="draggable" id="ar_left"
             onmousedown="drag()"
             src="{{ url_for('editing.render_img', filename='arrow_left.png') }}"
             alt="An arrow pointing up and to the left.">
        <img class="draggable" id="highlight"
             onmousedown="drag()"
             src="{{ url_for('editing.render_img', filename='highlight.png') }}"
             alt="A translucent yellow box.">
    </div>
</div>

<div id="textpop" style="display: none;width:1000px;">
    <br>
    <div class="col-sm-10">
        <input type="text" class="form-control"
               placeholder="Enter text here..."
               id="textToGenerate">
    </div>
    <br>
    <div class="row">
        <div class="col-sm-6">
            <i>Select a text color: </i> <br>
            <input type="radio" id="red" value="red" name="color">
            <label for="red">Red</label>
            <br>
            <input type="radio" id="blue" value="blue" name="color">
            <label for="black">Blue</label>
            <br>
            <input type="radio" id="black" value="black" name="color">
            <label for="black">Black</label>
            <br>
            <br>
        </div>
        <div class="col-sm-6">
            <i>Select a text size: </i><br>
            <input type="radio" id="sm" value="20" name="size">
            <label for="sm">Small</label>
            <br>
            <input type="radio" id="med" value="30" name="size">
            <label for="med">Medium</label>
            <br>
            <input type="radio" id="lg" value="40" name="size">
            <label for="lg">Large</label>
            <br>
            <br>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12" align="center">
            <button id="generate" class="btn btn-dark">
                Generate Text
            </button>
        </div>
    </div>
    <br>
    <div class="draggable" id="generatedText" onmousedown="drag()"></div>
</div>
<div id="trimpop" style="display:none">
    <div class="form-group">
        <div v-for="(video,index) in videos" :key="index">
            <label for="start_trim">Start:</label>
            <input id="start_trim" min="0" max="120" type="number"
                   value="0">
            <label for="end_trim">End: </label>
            <input id="end_trim" min="0" max="120" type="number"
                   value="0">
        </div>
    </div>
    <br>
    <div v-else>
        <div v-for="(video,index) in videos" :key="index" align="center">
            <button class="btn btn-info" id="trimclip"
                    v-on:click="buttonChecker(videos, index, 'trim')">
                Trim Clip
            </button>
        </div>
    </div>
</div>

<!--Modal with duration buttons that appears after dragging and dropping a shape-->
<div class="modal fade" id="durationModal" tabindex="-1" role="dialog" aria-labelledby="durationModalLabel"
     aria-hidden="true" v-for="(video,index) in videos" :key="index">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="durationModalLabel" align="center">How long would you like this
                    shape to
                    appear on the video?</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" align="center">
                         <span>
                            <button class="btn btn-secondary" id="1" v-on:click="setStartAndDuration(index, 1)">1s from starting time</button>
                            <button class="btn btn-secondary" id="5" v-on:click="setStartAndDuration(index, 5)">5s from starting time</button>
                            <br><br>
                            <button class="btn btn-secondary" id="10" v-on:click="setStartAndDuration(index, 10)">10s from starting time</button>
                            <button class="btn btn-secondary" id="all" v-on:click="setStartAndDuration(index, 18)">Entire video</button>
                        </span>
                <br><br>
                <label for="start_pos">Starting time:</label>
                <input id="start_pos" min="0" max="18" type="number" value="0">
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!--Modal for uploading videos-->
<div class="modal fade" id="importModal" tabindex="-1" role="dialog" aria-labelledby="importModalLabel"
     aria-hidden="true" v-for="(video,index) in videos" :key="index">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="importModalLabel" align="center">Please upload a video to begin.</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" align="center">
                <div id="uploadstuff">
                    <div>
                        <div class="form-group">
                            <input type="file" id="fileinput">
                            <br><br>
                            <div class="row">
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" placeholder="Clip Name"
                                           id="clipname">
                                </div>
                                <div class="col-sm-4">
                                    <button class="btn btn-primary" id="upload"> Upload
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal that appears when video is rendering -->
<div id="loaderModal" class="modal fade" role="dialog" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div align="center">
                <div class="loader"></div>
                <br>
                <b>Rendering... Please wait</b>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"
        integrity="sha512-bZS47S7sPOxkjU/4Bt0zrhEtWx0y0CRkhEp8IckzK+ltifIIE9EMIMTuT/mEzoIMewUINruDBIR/jJnbguonqQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="text/javascript" src="{{url_for('static', filename='video.js')}}"></script>

</body>
</html>

templates/index.html
<!-- /templates/index.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Welcome to VideoLab</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="icon" type="image/x-icon" href="/static/favicon.ico">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>

    <style>
        .version-header {
            border-bottom: 2px solid black;
            position:fixed;
            width:100%;
            overflow:auto;
            background:grey;
        }
        .app-select {
            align:center;
            text-align:center;
        }

    </style>
</head>
<body>
<div class="row version-header">
    <h5 align="left">VideoLab v. 0.1</h5>
</div>
<br> <br>
<div class="container">
    <h3 align="center">Welcome to VideoLab</h3>
    <br>
    <div class="row-lg-4" align="center"><a href="{{ url_for('goals') }}" class="btn btn-warning">New to VideoLab?
        Take a tour!</a></div>
    <br><br>
    <div class="app-select">
        <h3>Select an app to record:</h3>
        <br>
        <select>
            <option value="1"> App 1</option>
            <option value="2"> App 2</option>
            <option value="3"> App 3</option>
            <option value="4"> App 4</option>
            <option value="5"> App 5</option>
        </select>
        <br>
        <br>
        <a href="{{ url_for('editing.edit_video') }}" class="btn btn-danger">Start Recording</a>
        <br>
        <br>
    </div>
</div>


</body>
</html>

templates/recording.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Welcome to BugSwatter</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <style>
        .version-header {
            border-bottom: 2px solid black;
        }
    </style>
</head>
<body>
<div class="row version-header">
    <div class="col"><h5 align="left" >BugSwatter v. 0.1</h5></div>
    <div class="col"><h5 align="right" style="font-weight:bold">Recording: Step 1</h5></div>
</div>
<br> <br>
    <div class ="container">
        yeah fortnite we bout to get down (get down) we the hottest in the world right now just touched down on tomato town
    </div>


</body>
</html>

templates/tutorial.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Welcome to BugSwatter</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>

    <style>
        .version-header {
            border-bottom: 2px solid black;
        }

    </style>
</head>
<body>
<div class="row version-header">
    <div class="col"><h5 align="left">BugSwatter v. 0.1</h5></div>
    <div class="col"><h5 align="right" style="font-weight:bold">Our Mission and Video Guidelines</h5></div>
</div>
<br> <br>
<div class="container">
    Sample text
</div>


</body>
</html>